import { use } from "react";

import { Inter } from "next/font/google";
import { notFound } from "next/navigation";

import { Toaster } from "@/components/ui/sonner";
import { Locale } from "@/lib/i18n/locale";
import { routing } from "@/lib/i18n/routing";

import Providers from "../providers/providers";

import type { Metadata } from "next";

import "../globals.css";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Hestia",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return Object.values(Locale).map((locale) => ({ locale }));
}

export default function RootLayout(
  props: Readonly<{
    children: React.ReactNode;
    params: Promise<{ locale: Locale }>;
  }>
) {
  const params = use(props.params);

  const { locale } = params;

  const { children } = props;

  if (!routing.locales.includes(locale)) {
    notFound();
  }

  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={`${inter.className} antialiased`}>
        <Providers>{children}</Providers>
        <Toaster />
      </body>
    </html>
  );
}
